[package]
name = "simulate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
gloo = "0.11.0"
indicatif = "0.17.8"
itertools = "0.12.1"
ndarray = "0.15.6"
plotters = "0.3.5"
rand = "0.8.5"
rand_distr = "0.4.3"
reqwest = "0.12.2"
rstest = "0.18.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
wasm-bindgen-futures = "0.4.42"
yew = { version = "0.20.0", features = ["csr"] }
